routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/director', 'DirectorController', ['except' => [
	'destroy',
]]);

Route::resource('/actor', 'ActorController', ['except' => [
	'destroy',
]]);

Route::resource('/film', 'FilmController', ['except' => [
	'destroy',
]]);

Route::resource('/user', 'UserController');

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/listActor', 'PublicController@listActor')->name('listActor');
Route::get('/showActor/{actor}', 'PublicController@showActor')->name('showActor');
Route::get('/listDirector', 'PublicController@listDirector')->name('listDirector');
Route::get('/showDirector/{director}', 'PublicController@showDirector')->name('showDirector');
Route::get('/listFilm', 'PublicController@listFilm')->name('listFilm');
Route::get('/showFilm/{film}', 'PublicController@showFilm')->name('showFilm');

app/Actor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Actor extends Model
{
    /**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'gender',
		'born',
	];
	
	/**
	 * Get the films belong to the actor.
	 */
	public function films()
	{
		return $this->belongsToMany(Film::class);
	}	
}

app/Http/Controllers/ActorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Actor;

class ActorController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	
    /**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$this->authorize('create', Actor::class);
		
		$actor = new Actor();
		
		return view('actors.create', [
			'actor' => $actor,
		]);
	}
	
    /**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$this->authorize('create', Actor::class);
		
		$request->validate([
			'name' => 'required|max:100',
			'gender' => 'required',
			'born' => [
				'required',
				'regex:/^([0-1]{1})([0-9]{1})\/([0-3]{1})([0-9]{1})\/([0-9]{4})$/',
			],
		]);
		
		$actor = new Actor();
		$actor->fill($request->all());
		$actor->born = date('Y-m-d',strtotime($actor->born));
		if ($actor->save())
		{
			$actor->films()->sync($request->films_id,false);
		}
		
		return redirect()->route('actor.index');
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request)
	{
		$this->authorize('view', Actor::class);
		
		$actors = Actor::orderBy('name', 'asc')
		->when($request->query('name'), function($query) use ($request) {
			return $query->where('name', 'like', '%'.$request->query('name').'%');
		})
		->when($request->query('gender'), function($query) use ($request) {
			return $query->where('gender', $request->query('gender'));
		})
		->when($request->query('born'), function($query) use ($request) {
			return $query->where('born', 'like', '%'.date('Y-m-d',strtotime($request->query('born'))).'%');
		})
		->paginate(10);
		
		return view('actors.index', [
			'actors' => $actors
		]);
	}
	
	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$this->authorize('view', Actor::class);
		
		$actor = Actor::find($id);
		if (!$actor) throw new ModelNotFoundException;
		
		return view('actors.show', [
			'actor' => $actor
		]);
	}
	
	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$actor = Actor::find($id);
		if(!$actor) throw new ModelNotFoundException;
		
		$this->authorize('manage', $actor);
		
		return view('actors.edit', [
			'actor' => $actor
		]);
	}
	
	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @param int $id
	 *
	 * return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$request->validate([
			'name' => 'required|max:100',
			'gender' => 'required',
			'born' => [
				'required',
				'regex:/^([0-1]{1})([0-9]{1})\/([0-3]{1})([0-9]{1})\/([0-9]{4})$/',
			],
		]);
		
		$actor = Actor::find($id);
		if(!$actor) throw new ModelNotFoundException;
		
		$this->authorize('manage', $actor);
		
		$actor->fill($request->all());
		$actor->born = date('Y-m-d',strtotime($actor->born));
		if ($actor->save())
		{
			$actor->films()->detach();
			if (count($request->films_id) > 0)
			{
				$actor->films()->sync($request->films_id,false);
			}
		}
		
		return redirect()->route('actor.index');
	}
}

resources/views/actors/_filters.blade.php
<?php

use App\Common;

?>
<section class="filters">
	<div class="panel-body">
		{!! Form::open([
			'route' => ['actor.index'],
			'method' => 'get',
			'class' => 'form-inline'
		]) !!}
		
		<div class="form-group">
			{!! Form::label('actor-name', 'Name', [
				'class' => 'control-label',
			]) !!}
			{!! Form::text('name', null, [
				'id' => 'actor-name',
				'class' => 'form-control',
				'maxlength' => 100,
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::label('actor-gender', 'Gender', [
				'class' => 'control-label',
			]) !!}
			{!! Form::select('gender', Common::$genders, null, [
				'class' => 'form-control',
				'placeholder' => '- All -',
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::label('actor-born', 'Born', [
				'class' => 'control-label',
			]) !!}
			{!! Form::text('born', null, [
				'id' => 'datepicker',
				'class' => 'form-control',
				'maxlength' => 10,
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::button('Filter', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
		</div>
		{!! Form::close() !!}
	</div>
</section>

resources/views/actors/create.blade.php
<?php

use App\Common;
use App\Film;

?>
@extends('layouts.app')

@section('content')
	
	@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
	
	<!-- Bootstrap Boilerplate... -->
	
	<div class="panel-body">
		<!-- New Actor Form -->
		{!! Form::model($actor, [
			'route' => ['actor.store'],
			'class' => 'form-horizontal'
		]) !!}
		
		<!-- Name -->
		<div class="form-group row">
			{!! Form::label('actor-name', 'Name', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('name', null, [
					'id' => 'actor-name',
					'class' => 'form-control',
					'maxlength' => 100,
				]) !!}
			</div>
		</div>
		
		<!-- Gender -->
		<div class="form-group row">
			{!! Form::label('gender', 'Gender', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				@foreach(Common::$genders as $key => $val)
					{!! Form::radio('gender', $key) !!} {{$val}}
				@endforeach
			</div>
		</div>
		
		<!-- Born -->
		<div class="form-group row">
			{!! Form::label('actor-born', 'Born', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('born', null, [
					'id' => 'datepicker',
					'class' => 'form-control',
				]) !!}
			</div>
		</div>
		
		<!-- Films -->
		<div class="form-group row">
			{!! Form::label('actor-film', 'Film(s)', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('films_id[]', 
					Film::pluck('name', 'id'),
					null, [
						'class' => 'form-control select2',
						'multiple' => 'multiple',
						'data-placeholder' => '- Select Film(s) -',
				]) !!}
			</div>
		</div>
		
		<!-- Submit Button -->
		<div class="form-group row">
			<div class="col-sm-offset-3 col-sm-6">
			{!! Form::button('Submit', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
			<a href="{{ route('actor.index') }}" class="btn btn-warning">Back</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
@endsection

resources/views/actors/edit.blade.php
<?php

use App\Common;
use App\Film;
?>
@extends('layouts.app')

@section('content')
	
	@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
	
	<!-- Bootstrap Boilerplate... -->
	
	<div class="panel-body">
		<!-- Edit Actor Form -->
		{!! Form::model($actor, [
			'route' => ['actor.update', $actor->id],
			'method' => 'put',
			'class' => 'form-horizontal'
		]) !!}
		
		<!-- Name -->
		<div class="form-group row">
			{!! Form::label('actor-name', 'Name', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('name', $actor->name, [
					'id' => 'actor-name',
					'class' => 'form-control',
					'maxlength' => 100,
				]) !!}
			</div>
		</div>
		
		<!-- Gender -->
		<div class="form-group row">
			{!! Form::label('gender', 'Gender', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				@foreach(Common::$genders as $key => $val)
					{!! Form::radio('gender', $key) !!} {{$val}}
				@endforeach
			</div>
		</div>
		
		<!-- Born -->
		<div class="form-group row">
			{!! Form::label('actor-born', 'Born', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('born', date('m/d/Y',strtotime($actor->born)), [
					'id' => 'datepicker',
					'class' => 'form-control',
				]) !!}
			</div>
		</div>
		
		<!-- Film -->
		<div class="form-group row">
			{!! Form::label('actor-film', 'Film(s)', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('films_id[]', 
					Film::pluck('name', 'id'),
					$actor->films, [
						'class' => 'form-control select2',
						'multiple' => 'multiple',
						'data-placeholder' => '- Select Film(s) -',
				]) !!}
			</div>
		</div>
		
		<!-- Submit Button -->
		<div class="form-group row">
			<div class="col-sm-offset-3 col-sm-6">
			{!! Form::button('Save', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
			<a href="{{ route('actor.index') }}" class="btn btn-warning">Back</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
@endsection

resources/views/actors/index.blade.php
<?php

use App\Common;

?>
@extends('layouts.app')
@section('content')

<!-- Bootstrap Boilerplate... -->
<div class="panel-body">
<a href="{{ route('actor.create') }}" class="btn btn-success">Create Actor</a>
@include('actors._filters')
	@if (count($actors) > 0)
		<table class="table table-striped task-table">
			<!-- Table Headings -->
			<thead>
				<tr>
					<th>No.</th>
					<th>Name</th>
					<th>Gender</th>
					<th>Born</th>
					<th>Created</th>
					<th>Actions</th>
				</tr>
			</thead>
			
			<!-- Table Body -->
			<tbody>
				@foreach ($actors as $i => $actor)
				<tr>
					<td class="table-text">
						<div>{{ $i+1 }}</div>
					</td>
					<td class="table-text">
						<div>
							{!! link_to_route(
								'actor.show',
								$title = $actor->name,
								$parameters = [
									'id' => $actor->id,
								]
							) !!}
						</div>
					</td>
					<td class="table-text">
						<div>{{ Common::$genders[$actor->gender] }}</div>
					</td>
					<td class="table-text">
						<div>{{ $actor->born }}</div>
					</td>
					<td class="table-text">
						<div>{{ $actor->created_at }}</div>
					</td>
					<td class="table-text">
						<div>
						{!! link_to_route(
							'actor.edit',
							$title = 'Edit',
							$parameters = [
								'id' => $actor->id,
							]
						) !!}
						</div>
					</td>
				</tr>
				@endforeach
				{{ $actors->links() }}
			</tbody>
		</table>
	@else
	<div>
		No records found
	</div>
	@endif
</div>
@endsection

resources/views/actors/show.blade.php
<?php

use App\Common;

?>
@extends('layouts.app')

@section('content')

	<!-- Bootstrap Boilerplate... -->

	<div class="panel-body">
	<a href="{{ route('actor.index') }}" class="btn btn-primary">Back to Actor List</a>
	<a href="{{ route('actor.edit', $actor->id) }}" class="btn btn-success">Update Information</a>
		<table class="table table-striped task-table">
			<!-- Table Headings -->
			<thead>
				<tr>
					<th>Attribute</th>
					<th>Value</th>
				</tr>
			</thead>
			<!-- Table Body -->
			<tbody>
				<tr>
					<td>Name</td>
					<td>{{ $actor->name }}</td>
				</tr>
				<tr>
					<td>Gender</td>
					<td>{{ Common::$genders[$actor->gender] }}</td>
				</tr>
				<tr>
					<td>Born</td>
					<td>{{ $actor->born }}</td>
				</tr>
				<tr>
					<td>Film(s)</td>
					<td>
						<ul>
							@foreach ($actor->films as $film)
								<li>
									<div>
										{!! link_to_route(
											'film.show',
											$title = $film->name,
											$parameters = [
												'id' => $film->id,
											]
										) !!}
									</div>
								</li>
							@endforeach
						</ul>
					</td>
				</tr>
				<tr>
					<td>Created</td>
					<td>{{ $actor->created_at }}</td>
				</tr>
				<tr>
					<td>Updated</td>
					<td>{{ $actor->updated_at }}</td>
				</tr>
			</tbody>
		</table>
	</div>

@endsection