routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/director', 'DirectorController', ['except' => [
	'destroy',
]]);

Route::resource('/actor', 'ActorController', ['except' => [
	'destroy',
]]);

Route::resource('/film', 'FilmController', ['except' => [
	'destroy',
]]);

Route::resource('/user', 'UserController');

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/listActor', 'PublicController@listActor')->name('listActor');
Route::get('/showActor/{actor}', 'PublicController@showActor')->name('showActor');
Route::get('/listDirector', 'PublicController@listDirector')->name('listDirector');
Route::get('/showDirector/{director}', 'PublicController@showDirector')->name('showDirector');
Route::get('/listFilm', 'PublicController@listFilm')->name('listFilm');
Route::get('/showFilm/{film}', 'PublicController@showFilm')->name('showFilm');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Silber\Bouncer\Database\HasRolesAndAbilities;

class User extends Authenticatable
{
    use Notifiable;
	use HasRolesAndAbilities;
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Bouncer;
class UserController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	
    /**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$this->authorize('create', User::class);
		
		$user = new User();
		
		return view('users.create', [
			'user' => $user,
		]);
	}
	
    /**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$request->validate([
			'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
		]);
		$this->authorize('create', User::class);
		$user = new User();
		$request->password = bcrypt($request->password);
		$user->fill($request->all());
		$user->password = bcrypt($user->password);
		if ($user->save())
		{
			Bouncer::assign($request->role)->to($user);
		}
		
		return redirect()->route('user.index');
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request)
	{
		$this->authorize('view', User::class);
		
		$users = User::orderBy('name', 'asc')
		->when($request->query('name'), function($query) use ($request) {
			return $query->where('name', 'like', '%'.$request->query('name').'%');
		})
		->when($request->query('email'), function($query) use ($request) {
			return $query->where('email', 'like', '%'.$request->query('email').'%');
		})
		->paginate(10);
		
		return view('users.index', [
			'users' => $users
		]);
	}
	
	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$this->authorize('view', User::class);
		
		$user = User::find($id);
		if (!$user) throw new ModelNotFoundException;
		
		return view('users.show', [
			'user' => $user
		]);
	}
	
	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$user = User::find($id);
		if(!$user) throw new ModelNotFoundException;
		$this->authorize('manage', $user);
		return view('users.edit', [
			'user' => $user
		]);
	}
	
	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @param int $id
	 *
	 * return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$request->validate([
			'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
		]);
		
		$user = User::find($id);
		if(!$user) throw new ModelNotFoundException;
		
		$this->authorize('manage', $user);
		
		$user->fill($request->all());
		
		$user->save();
		if ($user->isAn('admin') && $request->role == 'staff') {
			Bouncer::retract('admin')->from($user);
			Bouncer::assign($request->role)->to($user);
		} else if ($user->isNotAn('admin') && $request->role == 'admin') {
			Bouncer::retract('staff')->from($user);
			Bouncer::assign($request->role)->to($user);
		}
		return redirect()->route('user.index');
	}
	
	/**
	 * Remove the specified resource from storage
	 *
	 * @param int $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		User::destroy($id);
		return redirect()->route('user.index');
	}
}

resources/views/users/_filters.blade.php
<?php

use App\Common;

?>
<section class="filters">
	<div class="panel-body">
		{!! Form::open([
			'route' => ['user.index'],
			'method' => 'get',
			'class' => 'form-inline'
		]) !!}
		
		<div class="form-group">
			{!! Form::label('user-name', 'Name', [
				'class' => 'control-label',
			]) !!}
			{!! Form::text('name', null, [
				'id' => 'user-name',
				'class' => 'form-control',
				'maxlength' => 255,
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::label('user-email', 'Email', [
				'class' => 'control-label',
			]) !!}
			{!! Form::text('born', null, [
				'id' => 'user-email',
				'class' => 'form-control',
				'maxlength' => 255,
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::button('Filter', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
		</div>
		{!! Form::close() !!}
	</div>
</section>

resources/views/users/create.blade.php
<?php
use App\Common;
?>

@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('user.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>
						
                        <div class="form-group">
                            <label for="role" class="col-md-4 control-label">Role</label>
                            <div class="col-md-6">
                                <input type="radio" id="role" name="role" value="staff" required> Staff<br>
								<input type="radio" id="role" name="role" value="admin"> Admin
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Submit
                                </button>
								<a href="{{ route('user.index') }}" class="btn btn-warning">Back</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
<?php
use App\Common;
?>

@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Update Account Information</div>

                <div class="panel-body">
                    {!! Form::model($user, [
						'route' => ['user.update', $user->id],
						'method' => 'put',
						'class' => 'form-horizontal'
					]) !!}
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $user->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ $user->email }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
						
                        <div class="form-group">
                            <label for="role" class="col-md-4 control-label">Role</label>
                            <div class="col-md-6">
                                <input type="radio" id="role" name="role" value="staff" <?php if($user->isNotAn('admin')) echo "checked"; ?> required> Staff<br>
								<input type="radio" id="role" name="role" value="admin"  <?php if($user->isAn('admin')) echo "checked"; ?>> Admin  
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>
								<a href="{{ route('user.index') }}" class="btn btn-warning">Back</a>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
<?php

use App\Common;
?>
@extends('layouts.app')
@section('content')
<!-- Bootstrap Boilerplate... -->
<div class="panel-body">
	<a href="{{ route('user.create') }}" class="btn btn-success">Create Staff Account</a>
	@include('users._filters')
	@if (count($users) > 0)
		<table class="table table-striped task-table">
			<!-- Table Headings -->
			<thead>
				<tr>
					<th>No.</th>
					<th>Name</th>
					<th>Email</th>
					<th>Role</th>
					<th>Created</th>
					<th>Actions</th>
				</tr>
			</thead>
			
			<!-- Table Body -->
			<tbody>
				@foreach ($users as $i => $user)
				<tr>
					<td class="table-text">
						<div>{{ $i+1 }}</div>
					</td>
					<td class="table-text">
						<div>
							{!! link_to_route(
								'user.show',
								$title = $user->name,
								$parameters = [
									'id' => $user->id,
								]
							) !!}
						</div>
					</td>
					<td class="table-text">
						<div>{{ $user->email }}</div>
					</td>
					<td class="table-text">
						@if ($user->isAn('admin'))
						<div>{{ 'Admin' }}</div>
						@else
						<div>{{ 'Staff' }}</div>
						@endif
					</td>
					<td class="table-text">
						<div>{{ $user->created_at }}</div>
					</td>
					<td class="table-text">
						<div>
						{!! link_to_route(
							'user.edit',
							$title = 'Edit',
							$parameters = [
								'id' => $user->id,
							]
						) !!}
						</div>
						<form onsubmit="return confirm('Do you really want to delete?');" action="{{ route('user.destroy',[$user->id]) }}" method="POST" >
						{{ csrf_field() }}
						<input type="hidden" name="_method" value="DELETE" />
						<button type="submit">Delete</i></button>
						</form>
					</td>
				</tr>
				@endforeach
				{{ $users->links() }}
			</tbody>
		</table>
	@else
	<div>
		No records found
	</div>
	@endif
</div>
@endsection

resources/views/users/show.blade.php
<?php

use App\Common;

?>
@extends('layouts.app')

@section('content')

	<!-- Bootstrap Boilerplate... -->

	<div class="panel-body">
	<a href="{{ route('user.index') }}" class="btn btn-primary">Back to Staff List</a>
	<a href="{{ route('user.edit', $user->id) }}" class="btn btn-success">Update Information</a>
		<table class="table table-striped task-table">
			<!-- Table Headings -->
			<thead>
				<tr>
					<th>Attribute</th>
					<th>Value</th>
				</tr>
			</thead>
			<!-- Table Body -->
			<tbody>
				<tr>
					<td>Name</td>
					<td>{{ $user->name }}</td>
				</tr>
				<tr>
					<td>Email</td>
					<td>{{ $user->email }}</td>
				</tr>
				<tr>
					<td>Role</td>
					@if ($user->isAn('admin'))
						<td>{{ 'Admin' }}</td>
					@else
						<td>{{ 'Staff' }}</td>
					@endif
				</tr>
				<tr>
					<td>Created</td>
					<td>{{ $user->created_at }}</td>
				</tr>
				<tr>
					<td>Updated</td>
					<td>{{ $user->updated_at }}</td>
				</tr>
			</tbody>
		</table>
	</div>

@endsection