routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/director', 'DirectorController', ['except' => [
	'destroy',
]]);

Route::resource('/actor', 'ActorController', ['except' => [
	'destroy',
]]);

Route::resource('/film', 'FilmController', ['except' => [
	'destroy',
]]);

Route::resource('/user', 'UserController');

//Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/listActor', 'PublicController@listActor')->name('listActor');
Route::get('/showActor/{actor}', 'PublicController@showActor')->name('showActor');
Route::get('/listDirector', 'PublicController@listDirector')->name('listDirector');
Route::get('/showDirector/{director}', 'PublicController@showDirector')->name('showDirector');
Route::get('/listFilm', 'PublicController@listFilm')->name('listFilm');
Route::get('/showFilm/{film}', 'PublicController@showFilm')->name('showFilm');

app/Film.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    /**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'release_date',
		'country',
		'runtime',
		'genre',
		'synopsis',
		'director_id',
	];
	
    /**
	 * Get the director of the film.
	 */
	public function director()
	{
		return $this->belongsTo(Director::class);
	}
	
	/**
	 * Get the actors belong to the film.
	 */
	public function actors()
	{
		return $this->belongsToMany(Actor::class);
	}
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Film;

class FilmController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	
    /**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$this->authorize('create', Film::class);
		
		$film = new Film();
		
		return view('films.create', [
			'film' => $film,
		]);
	}
	
    /**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$this->authorize('create', Film::class);
		
		$request->validate([
			'name' => 'required|max:100|unique:films',
			'release_date' => [
				'required',
				'regex:/^([0-1]{1})([0-9]{1})\/([0-3]{1})([0-9]{1})\/([0-9]{4})$/',
			],
			'country' => 'required',
			'runtime' => [
				'required',
				'regex:/^([0-2]{0,1})([0-9]{1})\:([0-5]{1})([0-9]{1})\:([0-5]{1})([0-9]{1})$/',
			],
			'genre' => 'required',
			'synopsis' => 'required',
			'director_id' => 'required',
			'actors_id' => 'required',
		]);
		
		$film = new Film();
		$film->fill($request->all());
		$film->release_date = date('Y-m-d',strtotime($film->release_date));
		if ($film->save())
		{
			$film->actors()->sync($request->actors_id,false);
		}
		
		return redirect()->route('film.index');
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request)
	{
		$this->authorize('view', Film::class);
		
		$films = Film::orderBy('name', 'asc')
		->when($request->query('name'), function($query) use ($request) {
			return $query->where('name', 'like', '%'.$request->query('name').'%');
		})
		->when($request->query('release_date'), function($query) use ($request) {
			return $query->where('release_date', 'like', '%'.date('Y-m-d',strtotime($request->query('release_date'))).'%');
		})
		->when($request->query('country'), function($query) use ($request) {
			return $query->where('country', $request->query('country'));
		})
		->when($request->query('genre'), function($query) use ($request) {
			return $query->where('genre', $request->query('genre'));
		})
		->paginate(10);
		
		return view('films.index', [
			'films' => $films
		]);
	}
	
	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$this->authorize('view', Film::class);
		
		$film = Film::find($id);
		if (!$film) throw new ModelNotFoundException;
		
		return view('films.show', [
			'film' => $film
		]);
	}
	
	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$film = Film::find($id);
		if(!$film) throw new ModelNotFoundException;
		$this->authorize('manage', $film);
		return view('films.edit', [
			'film' => $film
		]);
	}
	
	/**
	 * Update the specified resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @param int $id
	 *
	 * return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$request->validate([
			'name' => 'required|max:100|unique:films,name,'.$id,
			'release_date' => [
				'required',
				'regex:/^([0-1]{1})([0-9]{1})\/([0-3]{1})([0-9]{1})\/([0-9]{4})$/',
			],
			'country' => 'required',
			'runtime' => [
				'required',
				'regex:/^([0-2]{0,1})([0-9]{1})\:([0-5]{1})([0-9]{1})\:([0-5]{1})([0-9]{1})$/',
			],
			'genre' => 'required',
			'synopsis' => 'required',
			'director_id' => 'required',
			'actors_id' => 'required',
		]);
		
		$film = Film::find($id);
		if(!$film) throw new ModelNotFoundException;
		
		$this->authorize('manage', $film);
		
		$film->fill($request->all());
		$film->release_date = date('Y-m-d',strtotime($film->release_date));
		if ($film->save())
		{
			$film->actors()->detach();
			$film->actors()->sync($request->actors_id,false);
		}
		
		return redirect()->route('film.index');
	}
}

resources/views/films/_filters.blade.php
<?php

use App\Common;

?>
<section class="filters">
	<div class="panel-body">
		{!! Form::open([
			'route' => ['film.index'],
			'method' => 'get',
			'class' => 'form-inline'
		]) !!}
		
		<div class="form-group">
			{!! Form::label('film-name', 'Name', [
				'class' => 'control-label',
			]) !!}
			{!! Form::text('name', null, [
				'id' => 'film-name',
				'class' => 'form-control',
				'maxlength' => 100,
			]) !!}
		</div>

		<div class="form-group">
			{!! Form::label('film-release-date', 'Release Date', [
				'class' => 'control-label',
			]) !!}
			{!! Form::text('release_date', null, [
				'id' => 'datepicker',
				'class' => 'form-control',
				'maxlength' => 10,
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::label('film-country', 'Country', [
				'class' => 'control-label',
			]) !!}
			{!! Form::select('country', Common::$countries, null, [
				'class' => 'form-control',
				'placeholder' => '- All -',
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::label('film-genre', 'Genre', [
				'class' => 'control-label',
			]) !!}
			{!! Form::select('genre', Common::$genres, null, [
				'class' => 'form-control',
				'placeholder' => '- All -',
			]) !!}
		</div>
		
		<div class="form-group">
			{!! Form::button('Filter', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
		</div>
		{!! Form::close() !!}
	</div>
</section>

resources/views/films/create.blade.php
<?php

use App\Common;
use App\Director;
use App\Actor;

?>
@extends('layouts.app')

@section('content')

	@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
	
	<!-- Bootstrap Boilerplate... -->
	
	<div class="panel-body">
		<!-- New Film Form -->
		{!! Form::model($film, [
			'route' => ['film.store'],
			'class' => 'form-horizontal'
		]) !!}
		
		<!-- Name -->
		<div class="form-group row">
			{!! Form::label('film-name', 'Name', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('name', null, [
					'id' => 'film-name',
					'class' => 'form-control',
					'maxlength' => 100,
				]) !!}
			</div>
		</div>
		
		<!-- Release Date -->
		<div class="form-group row">
			{!! Form::label('film-release-date', 'Release Date', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('release_date', null, [
					'id' => 'datepicker',
					'class' => 'form-control',
				]) !!}
			</div>
		</div>
		
	    <!-- Country -->
	    <div class="form-group row">
			{!! Form::label('film-country', 'Country', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('country', Common::$countries, null, [
					'class' => 'form-control',
					'placeholder' => '- Select Country -',
				]) !!}
			</div>
	    </div>
	   
		<!-- Run Time -->
		<div class="form-group row">
			{!! Form::label('film-runtime', 'Runtime', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('runtime', null, [
					'id' => 'timepicker',
					'class' => 'form-control',
					'maxlength' => 100,
				]) !!}
			</div>
		</div>
		
	    <!-- Genre -->
	    <div class="form-group row">
			{!! Form::label('film-genre', 'Genre', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('genre', Common::$genres, null, [
					'class' => 'form-control',
					'placeholder' => '- Select Genre -',
				]) !!}
			</div>
	    </div>
		
		<!-- Synopsis -->
		<div class="form-group row">
			{!! Form::label('film-synopsis', 'Synopsis', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::textarea('synopsis', null, [
					'id' => 'film-synopsis',
					'class' => 'form-control',
				]) !!}
			</div>
		</div>

		<!-- Director -->
		<div class="form-group row">
			{!! Form::label('film-director', 'Director', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('director_id', 
					Director::pluck('name', 'id'),
					null, [
						'class' => 'form-control',
						'placeholder' => '- Select Director -',
				]) !!}
			</div>
		</div>
		
        <!-- Actor -->
		<div class="form-group row">
			{!! Form::label('film-actor', 'Starring(s)', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('actors_id[]', 
					Actor::pluck('name', 'id'),
					null, [
						'class' => 'form-control select2',
						'multiple' => 'multiple',
						'data-placeholder' => '- Select Starring(s) -',
				]) !!}
			</div>
		</div>
		
		<!-- Submit Button -->
		<div class="form-group row">
			<div class="col-sm-offset-3 col-sm-6">
			{!! Form::button('Submit', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
			<a href="{{ route('film.index') }}" class="btn btn-warning">Back</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
@endsection

resources/views/films/edit.blade.php
<?php

use App\Common;
use App\Director;
use App\Actor;

?>
@extends('layouts.app')

@section('content')
	
	@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div>
	@endif
	
	<!-- Bootstrap Boilerplate... -->
	
	<div class="panel-body">
		<!-- Edit Film Form -->
		{!! Form::model($film, [
			'route' => ['film.update', $film->id],
			'method' => 'put',
			'class' => 'form-horizontal'
		]) !!}
		
		<!-- Name -->
		<div class="form-group row">
			{!! Form::label('film-name', 'Name', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('name', $film->name, [
					'id' => 'film-name',
					'class' => 'form-control',
					'maxlength' => 100,
				]) !!}
			</div>
		</div>
		
		<!-- Release Date -->
		<div class="form-group row">
			{!! Form::label('film-release-date', 'Release Date', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('release_date', date('m/d/Y',strtotime($film->release_date)), [
					'id' => 'datepicker',
					'class' => 'form-control',
				]) !!}
			</div>
		</div>
		
	    <!-- Country -->
	    <div class="form-group row">
			{!! Form::label('film-country', 'Country', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('country', Common::$countries, $film->country, [
					'class' => 'form-control',
					'placeholder' => '- Select Country -',
				]) !!}
			</div>
	    </div>
	   
		<!-- Run Time -->
		<div class="form-group row">
			{!! Form::label('film-runtime', 'Runtime', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::text('runtime', $film->runtime, [
					'id' => 'timepicker',
					'class' => 'form-control',
					'maxlength' => 100,
				]) !!}
			</div>
		</div>
		
	    <!-- Genre -->
	    <div class="form-group row">
			{!! Form::label('film-genre', 'Genre', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('genre', Common::$genres, $film->genre, [
					'class' => 'form-control',
					'placeholder' => '- Select Genre -',
				]) !!}
			</div>
	    </div>
		
		<!-- Synopsis -->
		<div class="form-group row">
			{!! Form::label('film-synopsis', 'Synopsis', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::textarea('synopsis', $film->synopsis, [
					'id' => 'film-synopsis',
					'class' => 'form-control',
				]) !!}
			</div>
		</div>

		<!-- Director -->
		<div class="form-group row">
			{!! Form::label('film-director', 'Director', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('director_id', 
					Director::pluck('name', 'id'),
					null, [
						'class' => 'form-control',
						'placeholder' => '- Select Director -',
				]) !!}
			</div>
		</div>
		
        <!-- Actor -->
		<div class="form-group row">
			{!! Form::label('film-actor', 'Starring', [
				'class' => 'control-label col-sm-3',
			]) !!}
			<div class="col-sm-9">
				{!! Form::select('actors_id[]', 
					Actor::pluck('name', 'id'),
					$film->actors, [
						'class' => 'form-control select2',
						'multiple' => 'multiple',
						'data-placeholder' => '- Select Starring(s) -',
				]) !!}
			</div>
		</div>
		
		<!-- Submit Button -->
		<div class="form-group row">
			<div class="col-sm-offset-3 col-sm-6">
			{!! Form::button('Save', [
				'type' => 'submit',
				'class' => 'btn btn-primary',
			]) !!}
			<a href="{{ route('film.index') }}" class="btn btn-warning">Back</a>
			</div>
		</div>
		{!! Form::close() !!}
	</div>
@endsection

resources/views/films/index.blade.php
<?php

use App\Common;

?>
@extends('layouts.app')
@section('content')

<!-- Bootstrap Boilerplate... -->
<div class="panel-body">
<a href="{{ route('film.create') }}" class="btn btn-success">Create Film</a>
@include('films._filters')
	@if (count($films) > 0)
		<table class="table table-striped task-table">
			<!-- Table Headings -->
			<thead>
				<tr>
					<th>No.</th>
					<th>Name</th>
					<th>Release Date</th>
					<th>Country</th>
					<th>Runtime</th>
					<th>Genre</th>
					<th>Created</th>
					<th>Actions</th>
				</tr>
			</thead>
			
			<!-- Table Body -->
			<tbody>
				@foreach ($films as $i => $film)
				<tr>
					<td class="table-text">
						<div>{{ $i+1 }}</div>
					</td>
					<td class="table-text">
						<div>
							{!! link_to_route(
								'film.show',
								$title = $film->name,
								$parameters = [
									'id' => $film->id,
								]
							) !!}
						</div>
					</td>
					<td class="table-text">
						<div>{{ $film->release_date }}</div>
					</td>
					<td class="table-text">
						<div>{{ Common::$countries[$film->country] }}</div>
					</td>
					<td class="table-text">
						<div>{{ $film->runtime }}</div>
					</td>
					<td class="table-text">
						<div>{{ Common::$genres[$film->genre] }}</div>
					</td>
					<td class="table-text">
						<div>{{ $film->created_at }}</div>
					</td>
					<td class="table-text">
						<div>
						{!! link_to_route(
							'film.edit',
							$title = 'Edit',
							$parameters = [
								'id' => $film->id,
							]
						) !!}
						</div>
					</td>
				</tr>
				@endforeach
				{{ $films->links() }}
			</tbody>
		</table>
	@else
	<div>
		No records found
	</div>
	@endif
</div>
@endsection

resources/views/films/show.blade.php
<?php

use App\Common;

?>
@extends('layouts.app')

@section('content')

	<!-- Bootstrap Boilerplate... -->

	<div class="panel-body">
	<a href="{{ route('film.index') }}" class="btn btn-primary">Back to Film List</a>
	<a href="{{ route('film.edit', $film->id) }}" class="btn btn-success">Update Information</a>
		<table class="table table-striped task-table">
			<!-- Table Headings -->
			<thead>
				<tr>
					<th>Attribute</th>
					<th>Value</th>
				</tr>
			</thead>
			<!-- Table Body -->
			<tbody>
				<tr>
					<td>Name</td>
					<td>{{ $film->name }}</td>
				</tr>
				<tr>
					<td>Release Date</td>
					<td>{{ $film->release_date }}</td>
				</tr>
				<tr>
					<td>Country</td>
					<td>{{ Common::$countries[$film->country] }}</td>
				</tr>
				<tr>
					<td>Runtime</td>
					<td>{{ $film->runtime }}</td>
				</tr>
				<tr>
					<td>Genre</td>
					<td>{{ Common::$genres[$film->genre] }}</td>
				</tr>
				<tr>
					<td>Synopsis</td>
					<td>{{ $film->synopsis }}</td>
				</tr>
				<tr>
					<td>Director</td>
					<td>
						<div>
							{!! link_to_route(
								'director.show',
								$title = $film->director->name,
								$parameters = [
									'id' => $film->director->id,
								]
							) !!}
						</div>
					</td>
				</tr>
				<tr>
					<td>Starring(s)</td>
					<td>
						<ul>
							@foreach ($film->actors as $actor)
								<li>
								<div>
									{!! link_to_route(
										'actor.show',
										$title = $actor->name,
										$parameters = [
											'id' => $actor->id,
										]
									) !!}
								</div>
								</li>
							@endforeach
						</ul>
					</td>
				</tr>
				<tr>
					<td>Created</td>
					<td>{{ $film->created_at }}</td>
				</tr>
				<tr>
					<td>Updated</td>
					<td>{{ $film->updated_at }}</td>
				</tr>
			</tbody>
		</table>
	</div>

@endsection